// Layout: This file will be automatically created even if deleted

// Using title as an object
import { Metadata } from "next";
// Using Global Error file
import { ErrorWrapper } from "./error-wrapper";
import { ThemeProvider } from "./components/theme-provider";


import Header from "./_lib/header";
import Footer from "./_lib/footer";

export const metadata : Metadata = {
  title: {
    default: "The Default Fallback Title", // Fallback
    template: "%s | Prefix-Sufix", // Prefix/sufix
    // absolute:"" // Free from parent
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeProvider/>
      <body>
        <Header/>
        {/* {children} */}
         <ErrorWrapper>{children}</ErrorWrapper>
        <Footer/>
      </body>
    </html>
  )
}
